theme: jekyll-theme-minimal
logo: Foto.jpg
title: Kevin Griesbach
description: iOS Developer based in <a href="https://maps.apple.com/?address=Wiesdorfer%20Platz,%2051373%20Leverkusen,%20Germany&t=h">Leverkusen</a>
